language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t hitwjj/docker-react  -f Dockerfile.dev .

script:
  - docker run -e CI=true hitwjj/docker-react npm run test -- --coverage
